// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserLoginRequest {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserLoginResponse {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserLogoutRequest {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserLogoutResponse {
    #[prost(int64, tag = "1")]
    pub state: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserRegisterRequest {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub phone: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserRegisterResponse {
    #[prost(int64, tag = "1")]
    pub state: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyTokenRequest {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub request_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyTokenResponse {
    #[prost(int64, tag = "1")]
    pub state: i64,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub username: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddQuestionRequest {
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub content: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub create_by: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddQuestionResponse {
    #[prost(uint64, tag = "2")]
    pub id: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteQuestionRequest {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteQuestionResponse {
    #[prost(int64, tag = "1")]
    pub state: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateQuestionRequest {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub content: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub update_by: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateQuestionResponse {
    #[prost(int64, tag = "1")]
    pub state: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AnswerEntity {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(uint64, tag = "2")]
    pub question_id: u64,
    #[prost(string, tag = "3")]
    pub content: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub create_by: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub agree_count: u64,
    #[prost(bool, tag = "6")]
    pub has_aggreed: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddAnswerRequest {
    #[prost(message, optional, tag = "1")]
    pub answer: ::core::option::Option<AnswerEntity>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddAnswerResponse {
    #[prost(uint64, tag = "1")]
    pub id: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteAnswerRequest {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteAnswerResponse {
    #[prost(int64, tag = "1")]
    pub state: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateAnswerRequest {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub content: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub username: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateAnswerResponse {
    #[prost(int64, tag = "1")]
    pub state: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgreeAnswerRequest {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub create_by: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub action: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgreeAnswerResponse {
    #[prost(int64, tag = "1")]
    pub state: i64,
    #[prost(uint64, tag = "2")]
    pub agree_count: u64,
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QuestionDetailRequest {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QuestionEntity {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub content: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub create_by: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub read_count: u64,
    #[prost(uint64, tag = "6")]
    pub reply_count: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QuestionDetailResponse {
    #[prost(message, optional, tag = "1")]
    pub question: ::core::option::Option<QuestionEntity>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LatestQuestionRequest {
    #[prost(uint64, tag = "2")]
    pub last_id: u64,
    #[prost(uint64, tag = "3")]
    pub limit: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LatestQuestionResponse {
    #[prost(message, repeated, tag = "1")]
    pub questions: ::prost::alloc::vec::Vec<QuestionEntity>,
    #[prost(uint64, tag = "2")]
    pub last_id: u64,
    #[prost(bool, tag = "3")]
    pub is_end: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AnswerListRequest {
    #[prost(uint64, tag = "1")]
    pub question_id: u64,
    #[prost(uint64, tag = "2")]
    pub page: u64,
    #[prost(uint64, tag = "3")]
    pub limit: u64,
    #[prost(string, tag = "4")]
    pub username: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnswerListResponse {
    #[prost(message, repeated, tag = "1")]
    pub answers: ::prost::alloc::vec::Vec<AnswerEntity>,
    #[prost(uint64, tag = "2")]
    pub total: u64,
    #[prost(uint64, tag = "3")]
    pub total_page: u64,
    #[prost(uint64, tag = "4")]
    pub page_size: u64,
    #[prost(uint64, tag = "5")]
    pub current_page: u64,
    #[prost(bool, tag = "6")]
    pub is_end: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AnswerDetailRequest {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AnswerDetailResponse {
    #[prost(message, optional, tag = "1")]
    pub answer: ::core::option::Option<AnswerEntity>,
}
/// Generated client implementations.
pub mod qa_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct QaServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl QaServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> QaServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> QaServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            QaServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn user_login(
            &mut self,
            request: impl tonic::IntoRequest<super::UserLoginRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UserLoginResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/pb.QAService/UserLogin");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("pb.QAService", "UserLogin"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn user_logout(
            &mut self,
            request: impl tonic::IntoRequest<super::UserLogoutRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UserLogoutResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/pb.QAService/UserLogout");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("pb.QAService", "UserLogout"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn user_register(
            &mut self,
            request: impl tonic::IntoRequest<super::UserRegisterRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UserRegisterResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pb.QAService/UserRegister",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("pb.QAService", "UserRegister"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn verify_token(
            &mut self,
            request: impl tonic::IntoRequest<super::VerifyTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::VerifyTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/pb.QAService/VerifyToken");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("pb.QAService", "VerifyToken"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn add_question(
            &mut self,
            request: impl tonic::IntoRequest<super::AddQuestionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddQuestionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/pb.QAService/AddQuestion");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("pb.QAService", "AddQuestion"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete_question(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteQuestionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteQuestionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pb.QAService/DeleteQuestion",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pb.QAService", "DeleteQuestion"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_question(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateQuestionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateQuestionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pb.QAService/UpdateQuestion",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pb.QAService", "UpdateQuestion"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn add_answer(
            &mut self,
            request: impl tonic::IntoRequest<super::AddAnswerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddAnswerResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/pb.QAService/AddAnswer");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("pb.QAService", "AddAnswer"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete_answer(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteAnswerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteAnswerResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pb.QAService/DeleteAnswer",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("pb.QAService", "DeleteAnswer"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_answer(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateAnswerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateAnswerResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pb.QAService/UpdateAnswer",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("pb.QAService", "UpdateAnswer"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn agree_answer(
            &mut self,
            request: impl tonic::IntoRequest<super::AgreeAnswerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AgreeAnswerResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/pb.QAService/AgreeAnswer");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("pb.QAService", "AgreeAnswer"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn question_detail(
            &mut self,
            request: impl tonic::IntoRequest<super::QuestionDetailRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QuestionDetailResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pb.QAService/QuestionDetail",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pb.QAService", "QuestionDetail"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn latest_question(
            &mut self,
            request: impl tonic::IntoRequest<super::LatestQuestionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LatestQuestionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pb.QAService/LatestQuestion",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pb.QAService", "LatestQuestion"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn answer_list(
            &mut self,
            request: impl tonic::IntoRequest<super::AnswerListRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AnswerListResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/pb.QAService/AnswerList");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("pb.QAService", "AnswerList"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn answer_detail(
            &mut self,
            request: impl tonic::IntoRequest<super::AnswerDetailRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AnswerDetailResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pb.QAService/AnswerDetail",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("pb.QAService", "AnswerDetail"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn answer_agree(
            &mut self,
            request: impl tonic::IntoRequest<super::AgreeAnswerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AgreeAnswerResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/pb.QAService/AnswerAgree");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("pb.QAService", "AnswerAgree"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod qa_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with QaServiceServer.
    #[async_trait]
    pub trait QaService: std::marker::Send + std::marker::Sync + 'static {
        async fn user_login(
            &self,
            request: tonic::Request<super::UserLoginRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UserLoginResponse>,
            tonic::Status,
        >;
        async fn user_logout(
            &self,
            request: tonic::Request<super::UserLogoutRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UserLogoutResponse>,
            tonic::Status,
        >;
        async fn user_register(
            &self,
            request: tonic::Request<super::UserRegisterRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UserRegisterResponse>,
            tonic::Status,
        >;
        async fn verify_token(
            &self,
            request: tonic::Request<super::VerifyTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::VerifyTokenResponse>,
            tonic::Status,
        >;
        async fn add_question(
            &self,
            request: tonic::Request<super::AddQuestionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddQuestionResponse>,
            tonic::Status,
        >;
        async fn delete_question(
            &self,
            request: tonic::Request<super::DeleteQuestionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteQuestionResponse>,
            tonic::Status,
        >;
        async fn update_question(
            &self,
            request: tonic::Request<super::UpdateQuestionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateQuestionResponse>,
            tonic::Status,
        >;
        async fn add_answer(
            &self,
            request: tonic::Request<super::AddAnswerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddAnswerResponse>,
            tonic::Status,
        >;
        async fn delete_answer(
            &self,
            request: tonic::Request<super::DeleteAnswerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteAnswerResponse>,
            tonic::Status,
        >;
        async fn update_answer(
            &self,
            request: tonic::Request<super::UpdateAnswerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateAnswerResponse>,
            tonic::Status,
        >;
        async fn agree_answer(
            &self,
            request: tonic::Request<super::AgreeAnswerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AgreeAnswerResponse>,
            tonic::Status,
        >;
        async fn question_detail(
            &self,
            request: tonic::Request<super::QuestionDetailRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QuestionDetailResponse>,
            tonic::Status,
        >;
        async fn latest_question(
            &self,
            request: tonic::Request<super::LatestQuestionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LatestQuestionResponse>,
            tonic::Status,
        >;
        async fn answer_list(
            &self,
            request: tonic::Request<super::AnswerListRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AnswerListResponse>,
            tonic::Status,
        >;
        async fn answer_detail(
            &self,
            request: tonic::Request<super::AnswerDetailRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AnswerDetailResponse>,
            tonic::Status,
        >;
        async fn answer_agree(
            &self,
            request: tonic::Request<super::AgreeAnswerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AgreeAnswerResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct QaServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> QaServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for QaServiceServer<T>
    where
        T: QaService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/pb.QAService/UserLogin" => {
                    #[allow(non_camel_case_types)]
                    struct UserLoginSvc<T: QaService>(pub Arc<T>);
                    impl<
                        T: QaService,
                    > tonic::server::UnaryService<super::UserLoginRequest>
                    for UserLoginSvc<T> {
                        type Response = super::UserLoginResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UserLoginRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as QaService>::user_login(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UserLoginSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pb.QAService/UserLogout" => {
                    #[allow(non_camel_case_types)]
                    struct UserLogoutSvc<T: QaService>(pub Arc<T>);
                    impl<
                        T: QaService,
                    > tonic::server::UnaryService<super::UserLogoutRequest>
                    for UserLogoutSvc<T> {
                        type Response = super::UserLogoutResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UserLogoutRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as QaService>::user_logout(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UserLogoutSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pb.QAService/UserRegister" => {
                    #[allow(non_camel_case_types)]
                    struct UserRegisterSvc<T: QaService>(pub Arc<T>);
                    impl<
                        T: QaService,
                    > tonic::server::UnaryService<super::UserRegisterRequest>
                    for UserRegisterSvc<T> {
                        type Response = super::UserRegisterResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UserRegisterRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as QaService>::user_register(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UserRegisterSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pb.QAService/VerifyToken" => {
                    #[allow(non_camel_case_types)]
                    struct VerifyTokenSvc<T: QaService>(pub Arc<T>);
                    impl<
                        T: QaService,
                    > tonic::server::UnaryService<super::VerifyTokenRequest>
                    for VerifyTokenSvc<T> {
                        type Response = super::VerifyTokenResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::VerifyTokenRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as QaService>::verify_token(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = VerifyTokenSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pb.QAService/AddQuestion" => {
                    #[allow(non_camel_case_types)]
                    struct AddQuestionSvc<T: QaService>(pub Arc<T>);
                    impl<
                        T: QaService,
                    > tonic::server::UnaryService<super::AddQuestionRequest>
                    for AddQuestionSvc<T> {
                        type Response = super::AddQuestionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AddQuestionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as QaService>::add_question(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AddQuestionSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pb.QAService/DeleteQuestion" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteQuestionSvc<T: QaService>(pub Arc<T>);
                    impl<
                        T: QaService,
                    > tonic::server::UnaryService<super::DeleteQuestionRequest>
                    for DeleteQuestionSvc<T> {
                        type Response = super::DeleteQuestionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeleteQuestionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as QaService>::delete_question(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteQuestionSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pb.QAService/UpdateQuestion" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateQuestionSvc<T: QaService>(pub Arc<T>);
                    impl<
                        T: QaService,
                    > tonic::server::UnaryService<super::UpdateQuestionRequest>
                    for UpdateQuestionSvc<T> {
                        type Response = super::UpdateQuestionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdateQuestionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as QaService>::update_question(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateQuestionSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pb.QAService/AddAnswer" => {
                    #[allow(non_camel_case_types)]
                    struct AddAnswerSvc<T: QaService>(pub Arc<T>);
                    impl<
                        T: QaService,
                    > tonic::server::UnaryService<super::AddAnswerRequest>
                    for AddAnswerSvc<T> {
                        type Response = super::AddAnswerResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AddAnswerRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as QaService>::add_answer(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AddAnswerSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pb.QAService/DeleteAnswer" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteAnswerSvc<T: QaService>(pub Arc<T>);
                    impl<
                        T: QaService,
                    > tonic::server::UnaryService<super::DeleteAnswerRequest>
                    for DeleteAnswerSvc<T> {
                        type Response = super::DeleteAnswerResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeleteAnswerRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as QaService>::delete_answer(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteAnswerSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pb.QAService/UpdateAnswer" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateAnswerSvc<T: QaService>(pub Arc<T>);
                    impl<
                        T: QaService,
                    > tonic::server::UnaryService<super::UpdateAnswerRequest>
                    for UpdateAnswerSvc<T> {
                        type Response = super::UpdateAnswerResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdateAnswerRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as QaService>::update_answer(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateAnswerSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pb.QAService/AgreeAnswer" => {
                    #[allow(non_camel_case_types)]
                    struct AgreeAnswerSvc<T: QaService>(pub Arc<T>);
                    impl<
                        T: QaService,
                    > tonic::server::UnaryService<super::AgreeAnswerRequest>
                    for AgreeAnswerSvc<T> {
                        type Response = super::AgreeAnswerResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AgreeAnswerRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as QaService>::agree_answer(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AgreeAnswerSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pb.QAService/QuestionDetail" => {
                    #[allow(non_camel_case_types)]
                    struct QuestionDetailSvc<T: QaService>(pub Arc<T>);
                    impl<
                        T: QaService,
                    > tonic::server::UnaryService<super::QuestionDetailRequest>
                    for QuestionDetailSvc<T> {
                        type Response = super::QuestionDetailResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::QuestionDetailRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as QaService>::question_detail(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = QuestionDetailSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pb.QAService/LatestQuestion" => {
                    #[allow(non_camel_case_types)]
                    struct LatestQuestionSvc<T: QaService>(pub Arc<T>);
                    impl<
                        T: QaService,
                    > tonic::server::UnaryService<super::LatestQuestionRequest>
                    for LatestQuestionSvc<T> {
                        type Response = super::LatestQuestionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LatestQuestionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as QaService>::latest_question(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LatestQuestionSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pb.QAService/AnswerList" => {
                    #[allow(non_camel_case_types)]
                    struct AnswerListSvc<T: QaService>(pub Arc<T>);
                    impl<
                        T: QaService,
                    > tonic::server::UnaryService<super::AnswerListRequest>
                    for AnswerListSvc<T> {
                        type Response = super::AnswerListResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AnswerListRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as QaService>::answer_list(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AnswerListSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pb.QAService/AnswerDetail" => {
                    #[allow(non_camel_case_types)]
                    struct AnswerDetailSvc<T: QaService>(pub Arc<T>);
                    impl<
                        T: QaService,
                    > tonic::server::UnaryService<super::AnswerDetailRequest>
                    for AnswerDetailSvc<T> {
                        type Response = super::AnswerDetailResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AnswerDetailRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as QaService>::answer_detail(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AnswerDetailSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pb.QAService/AnswerAgree" => {
                    #[allow(non_camel_case_types)]
                    struct AnswerAgreeSvc<T: QaService>(pub Arc<T>);
                    impl<
                        T: QaService,
                    > tonic::server::UnaryService<super::AgreeAnswerRequest>
                    for AnswerAgreeSvc<T> {
                        type Response = super::AgreeAnswerResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AgreeAnswerRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as QaService>::answer_agree(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AnswerAgreeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for QaServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "pb.QAService";
    impl<T> tonic::server::NamedService for QaServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
